allow-lan: true
bind-address: '*'
external-controller: 127.0.0.1:9090
log-level: info
mixed-port: 7890
mode: rule
proxies:
- name: HTTP-1
  port: 2999
  server: 174.137.134.182
  type: http
- name: HTTP-2
  port: 8888
  server: 159.224.232.194
  type: http
- name: HTTP-3
  port: 8888
  server: 122.116.125.115
  type: http
- name: HTTP-4
  port: 3128
  server: 47.84.84.1
  type: http
- name: HTTP-5
  port: 8080
  server: 103.227.210.164
  type: http
- name: HTTP-6
  port: 8080
  server: 103.51.223.133
  type: http
- name: HTTP-7
  port: 80
  server: 91.202.185.69
  type: http
- name: HTTP-8
  port: 9080
  server: 8.211.200.183
  type: http
- name: HTTP-9
  port: 6379
  server: 8.211.194.78
  type: http
- name: HTTP-10
  port: 6379
  server: 8.211.195.139
  type: http
- name: HTTP-11
  port: 80
  server: 8.211.49.86
  type: http
- name: HTTP-12
  port: 104
  server: 8.211.42.167
  type: http
- name: HTTP-13
  port: 8080
  server: 195.26.230.202
  type: http
- name: HTTP-14
  port: 20000
  server: 152.53.20.190
  type: http
- name: HTTP-15
  port: 80
  server: 8.219.97.248
  type: http
- name: HTTP-16
  port: 8080
  server: 5.45.126.128
  type: http
- name: HTTP-17
  port: 3129
  server: 47.91.121.127
  type: http
- name: HTTP-18
  port: 9080
  server: 8.213.222.157
  type: http
- name: HTTP-19
  port: 8080
  server: 31.10.83.158
  type: http
- name: HTTP-20
  port: 3128
  server: 8.213.195.191
  type: http
- name: HTTP-21
  port: 80
  server: 212.231.191.23
  type: http
- name: HTTP-22
  port: 3128
  server: 39.104.57.33
  type: http
- name: HTTP-23
  port: 8080
  server: 101.206.186.99
  type: http
- name: HTTP-24
  port: 3129
  server: 47.250.155.254
  type: http
- name: HTTP-25
  port: 11111
  server: 103.237.102.191
  type: http
- name: HTTP-26
  port: 5060
  server: 8.211.200.183
  type: http
- name: HTTP-27
  port: 8888
  server: 5.188.130.139
  type: http
- name: HTTP-28
  port: 8887
  server: 95.211.64.139
  type: http
- name: HTTP-29
  port: 8081
  server: 47.116.126.57
  type: http
- name: HTTP-30
  port: 8080
  server: 112.64.135.45
  type: http
- name: HTTP-31
  port: 80
  server: 178.212.144.7
  type: http
- name: HTTP-32
  port: 3128
  server: 152.42.167.241
  type: http
- name: HTTP-33
  port: 9098
  server: 8.213.195.191
  type: http
- name: HTTP-34
  port: 17981
  server: 116.196.150.180
  type: http
- name: HTTP-35
  port: 5060
  server: 8.211.51.115
  type: http
- name: HTTP-36
  port: 9050
  server: 47.251.73.54
  type: http
- name: HTTP-37
  port: 20002
  server: 8.211.195.173
  type: http
- name: HTTP-38
  port: 9098
  server: 8.213.197.208
  type: http
- name: HTTP-39
  port: 8080
  server: 169.58.85.194
  type: http
- name: HTTP-40
  port: 8080
  server: 47.76.144.139
  type: http
- name: HTTP-41
  port: 9098
  server: 8.138.131.110
  type: http
- name: HTTP-42
  port: 80
  server: 34.44.49.215
  type: http
- name: HTTP-43
  port: 3333
  server: 147.45.166.120
  type: http
- name: HTTP-44
  port: 9080
  server: 47.254.36.213
  type: http
- name: HTTP-45
  port: 8081
  server: 8.220.204.215
  type: http
- name: HTTP-46
  port: 3128
  server: 8.210.17.35
  type: http
- name: HTTP-47
  port: 37777
  server: 47.74.46.81
  type: http
- name: HTTP-48
  port: 3128
  server: 47.238.128.246
  type: http
- name: HTTP-49
  port: 80
  server: 103.151.20.131
  type: http
- name: HTTP-50
  port: 8888
  server: 95.211.64.139
  type: http
proxy-groups:
- name: Proxies
  proxies:
  - HTTP-1
  - HTTP-2
  - HTTP-3
  - HTTP-4
  - HTTP-5
  - HTTP-6
  - HTTP-7
  - HTTP-8
  - HTTP-9
  - HTTP-10
  - HTTP-11
  - HTTP-12
  - HTTP-13
  - HTTP-14
  - HTTP-15
  - HTTP-16
  - HTTP-17
  - HTTP-18
  - HTTP-19
  - HTTP-20
  - HTTP-21
  - HTTP-22
  - HTTP-23
  - HTTP-24
  - HTTP-25
  - HTTP-26
  - HTTP-27
  - HTTP-28
  - HTTP-29
  - HTTP-30
  - HTTP-31
  - HTTP-32
  - HTTP-33
  - HTTP-34
  - HTTP-35
  - HTTP-36
  - HTTP-37
  - HTTP-38
  - HTTP-39
  - HTTP-40
  - HTTP-41
  - HTTP-42
  - HTTP-43
  - HTTP-44
  - HTTP-45
  - HTTP-46
  - HTTP-47
  - HTTP-48
  - HTTP-49
  - HTTP-50
  type: select
- interval: 300
  name: Auto
  proxies:
  - HTTP-1
  - HTTP-2
  - HTTP-3
  - HTTP-4
  - HTTP-5
  - HTTP-6
  - HTTP-7
  - HTTP-8
  - HTTP-9
  - HTTP-10
  - HTTP-11
  - HTTP-12
  - HTTP-13
  - HTTP-14
  - HTTP-15
  - HTTP-16
  - HTTP-17
  - HTTP-18
  - HTTP-19
  - HTTP-20
  - HTTP-21
  - HTTP-22
  - HTTP-23
  - HTTP-24
  - HTTP-25
  - HTTP-26
  - HTTP-27
  - HTTP-28
  - HTTP-29
  - HTTP-30
  - HTTP-31
  - HTTP-32
  - HTTP-33
  - HTTP-34
  - HTTP-35
  - HTTP-36
  - HTTP-37
  - HTTP-38
  - HTTP-39
  - HTTP-40
  - HTTP-41
  - HTTP-42
  - HTTP-43
  - HTTP-44
  - HTTP-45
  - HTTP-46
  - HTTP-47
  - HTTP-48
  - HTTP-49
  - HTTP-50
  type: url-test
  url: http://www.gstatic.com/generate_204
rules:
- MATCH,Proxies
