allow-lan: true
bind-address: '*'
external-controller: 127.0.0.1:9090
log-level: info
mixed-port: 7890
mode: rule
proxies:
- name: HTTP-1
  port: 8081
  server: 23.228.86.236
  type: http
- name: HTTP-2
  port: 4857
  server: 138.197.68.35
  type: http
- name: HTTP-3
  port: 17981
  server: 58.254.153.146
  type: http
- name: HTTP-4
  port: 80
  server: 212.231.191.23
  type: http
- name: HTTP-5
  port: 3128
  server: 14.139.235.82
  type: http
- name: HTTP-6
  port: 80
  server: 185.135.69.34
  type: http
- name: HTTP-7
  port: 9090
  server: 219.142.66.244
  type: http
- name: HTTP-8
  port: 9080
  server: 47.252.11.233
  type: http
- name: HTTP-9
  port: 3128
  server: 8.209.96.245
  type: http
- name: HTTP-10
  port: 18081
  server: 8.220.204.215
  type: http
- name: HTTP-11
  port: 138
  server: 8.213.156.191
  type: http
- name: HTTP-12
  port: 8080
  server: 8.211.194.85
  type: http
- name: HTTP-13
  port: 1080
  server: 8.213.222.247
  type: http
- name: HTTP-14
  port: 80
  server: 47.91.29.151
  type: http
- name: HTTP-15
  port: 18080
  server: 164.52.11.194
  type: http
- name: HTTP-16
  port: 8080
  server: 8.221.139.222
  type: http
- name: HTTP-17
  port: 80
  server: 8.130.54.67
  type: http
- name: HTTP-18
  port: 10006
  server: 51.159.97.242
  type: http
- name: HTTP-19
  port: 2526
  server: 47.238.60.156
  type: http
- name: HTTP-20
  port: 3128
  server: 142.93.202.130
  type: http
- name: HTTP-21
  port: 8080
  server: 103.51.223.133
  type: http
- name: HTTP-22
  port: 80
  server: 197.221.240.247
  type: http
- name: HTTP-23
  port: 3128
  server: 77.242.177.57
  type: http
- name: HTTP-24
  port: 3128
  server: 195.19.217.200
  type: http
- name: HTTP-25
  port: 10801
  server: 8.211.49.86
  type: http
- name: HTTP-26
  port: 9080
  server: 8.148.4.166
  type: http
- name: HTTP-27
  port: 8086
  server: 125.122.35.253
  type: http
- name: HTTP-28
  port: 8008
  server: 8.130.74.114
  type: http
- name: HTTP-29
  port: 80
  server: 34.44.49.215
  type: http
- name: HTTP-30
  port: 3128
  server: 8.211.200.183
  type: http
- name: HTTP-31
  port: 8080
  server: 188.191.165.159
  type: http
- name: HTTP-32
  port: 8080
  server: 39.104.59.56
  type: http
- name: HTTP-33
  port: 8085
  server: 162.214.159.94
  type: http
- name: HTTP-34
  port: 8081
  server: 8.221.138.111
  type: http
- name: HTTP-35
  port: 5800
  server: 8.211.194.78
  type: http
- name: HTTP-36
  port: 45
  server: 47.74.46.81
  type: http
- name: HTTP-37
  port: 4002
  server: 47.238.134.126
  type: http
- name: HTTP-38
  port: 3128
  server: 47.91.89.3
  type: http
- name: HTTP-39
  port: 8008
  server: 8.211.195.173
  type: http
- name: HTTP-40
  port: 9000
  server: 8.213.128.6
  type: http
- name: HTTP-41
  port: 8443
  server: 47.116.210.163
  type: http
- name: HTTP-42
  port: 9080
  server: 8.211.42.167
  type: http
- name: HTTP-43
  port: 90
  server: 47.251.73.54
  type: http
- name: HTTP-44
  port: 3128
  server: 1.231.81.166
  type: http
- name: HTTP-45
  port: 8888
  server: 159.65.230.46
  type: http
- name: HTTP-46
  port: 8888
  server: 143.198.87.117
  type: http
- name: HTTP-47
  port: 8081
  server: 67.203.23.88
  type: http
- name: HTTP-48
  port: 999
  server: 47.252.18.37
  type: http
- name: HTTP-49
  port: 8083
  server: 8.221.141.88
  type: http
- name: HTTP-50
  port: 9098
  server: 8.211.51.115
  type: http
proxy-groups:
- name: Proxies
  proxies:
  - HTTP-1
  - HTTP-2
  - HTTP-3
  - HTTP-4
  - HTTP-5
  - HTTP-6
  - HTTP-7
  - HTTP-8
  - HTTP-9
  - HTTP-10
  - HTTP-11
  - HTTP-12
  - HTTP-13
  - HTTP-14
  - HTTP-15
  - HTTP-16
  - HTTP-17
  - HTTP-18
  - HTTP-19
  - HTTP-20
  - HTTP-21
  - HTTP-22
  - HTTP-23
  - HTTP-24
  - HTTP-25
  - HTTP-26
  - HTTP-27
  - HTTP-28
  - HTTP-29
  - HTTP-30
  - HTTP-31
  - HTTP-32
  - HTTP-33
  - HTTP-34
  - HTTP-35
  - HTTP-36
  - HTTP-37
  - HTTP-38
  - HTTP-39
  - HTTP-40
  - HTTP-41
  - HTTP-42
  - HTTP-43
  - HTTP-44
  - HTTP-45
  - HTTP-46
  - HTTP-47
  - HTTP-48
  - HTTP-49
  - HTTP-50
  type: select
- interval: 300
  name: Auto
  proxies:
  - HTTP-1
  - HTTP-2
  - HTTP-3
  - HTTP-4
  - HTTP-5
  - HTTP-6
  - HTTP-7
  - HTTP-8
  - HTTP-9
  - HTTP-10
  - HTTP-11
  - HTTP-12
  - HTTP-13
  - HTTP-14
  - HTTP-15
  - HTTP-16
  - HTTP-17
  - HTTP-18
  - HTTP-19
  - HTTP-20
  - HTTP-21
  - HTTP-22
  - HTTP-23
  - HTTP-24
  - HTTP-25
  - HTTP-26
  - HTTP-27
  - HTTP-28
  - HTTP-29
  - HTTP-30
  - HTTP-31
  - HTTP-32
  - HTTP-33
  - HTTP-34
  - HTTP-35
  - HTTP-36
  - HTTP-37
  - HTTP-38
  - HTTP-39
  - HTTP-40
  - HTTP-41
  - HTTP-42
  - HTTP-43
  - HTTP-44
  - HTTP-45
  - HTTP-46
  - HTTP-47
  - HTTP-48
  - HTTP-49
  - HTTP-50
  type: url-test
  url: http://www.gstatic.com/generate_204
rules:
- MATCH,Proxies
