# 自动生成 - fetch_nodes.py
mixed-port: 7890
allow-lan: false
mode: rule
log-level: info
external-controller: 127.0.0.1:9090

proxies:
  - {name: "HK 🇭🇰 | @Raydikalx | BA65C4", type: "vmess", server: "206.237.20.44", port: 55216, uuid: "154dbc39-0921-cf11-29bd-156c5000d763", alterId: 0, cipher: "auto", udp: True, network: "tcp"}
  - {name: "SG 🇸🇬 | @Raydikalx | E246D9", type: "vmess", server: "213.35.103.177", port: 53386, uuid: "32e75662-c1ed-4e8d-f78c-3dcc685cc795", alterId: 0, cipher: "auto", udp: True, network: "tcp"}
  - {name: "🇺🇸US-198.211.4.60-0012", type: "vmess", server: "198.211.4.60", port: 80, uuid: "1c65cfed-0b0c-4e21-92aa-90c9663a654f", alterId: 0, cipher: "auto", udp: True, network: "ws", ws-opts: {path: "/", headers: {"Host": "198.211.4.60"}}}
  - {name: "⚡ b2n.ir/v2ray-configs | 849", type: "trojan", server: "104.18.152.179", port: 443, password: "humanity", udp: True, skip-cert-verify: True, sni: "www.ignitelimit.com"}
  - {name: "⚡ b2n.ir/v2ray-configs | 46", type: "trojan", server: "104.18.152.187", port: 443, password: "humanity", udp: True, skip-cert-verify: True, sni: "www.ignitelimit.com"}
  - {name: "⚡ b2n.ir/v2ray-configs | 168", type: "trojan", server: "104.16.174.109", port: 443, password: "humanity", udp: True, skip-cert-verify: True, sni: "www.ignitelimit.com"}
  - {name: "DE 🇩🇪 | @Raydikalx | 1832ED", type: "vmess", server: "91.107.155.9", port: 59076, uuid: "8c692a4d-d223-470a-92b3-00c4b189ca73", alterId: 0, cipher: "auto", udp: True, network: "tcp"}
  - {name: "CA 🇨🇦 | @Raydikalx | 875198", type: "vmess", server: "tgju.org", port: 8080, uuid: "e8b1500b-e9e8-5492-8312-f4eadf7d0767", alterId: 0, cipher: "auto", udp: True, network: "ws", ws-opts: {path: "/nasnet/cdn", headers: {"Host": "nasnet-571296497.iranpress.co"}}}
  - {name: "⚡ b2n.ir/v2ray-configs | 684", type: "trojan", server: "104.16.174.124", port: 443, password: "humanity", udp: True, skip-cert-verify: True, sni: "www.ignitelimit.com"}
  - {name: "⚡ b2n.ir/v2ray-configs | 307", type: "trojan", server: "104.18.152.204", port: 443, password: "humanity", udp: True, skip-cert-verify: True, sni: "www.ignitelimit.com"}
  - {name: "⚡ b2n.ir/v2ray-configs | 808", type: "trojan", server: "104.18.152.144", port: 443, password: "humanity", udp: True, skip-cert-verify: True, sni: "www.ignitelimit.com"}
  - {name: "⚡ b2n.ir/v2ray-configs | 268", type: "ss", server: "14.29.124.168", port: 25219, cipher: "aes-128-cfb", password: "QazEdcTgb159@$*", udp: True}

proxy-groups:
  - name: 自动选择
    type: url-test
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    tolerance: 50
    proxies:
      - "HK 🇭🇰 | @Raydikalx | BA65C4"
      - "SG 🇸🇬 | @Raydikalx | E246D9"
      - "🇺🇸US-198.211.4.60-0012"
      - "⚡ b2n.ir/v2ray-configs | 849"
      - "⚡ b2n.ir/v2ray-configs | 46"
      - "⚡ b2n.ir/v2ray-configs | 168"
      - "DE 🇩🇪 | @Raydikalx | 1832ED"
      - "CA 🇨🇦 | @Raydikalx | 875198"
      - "⚡ b2n.ir/v2ray-configs | 684"
      - "⚡ b2n.ir/v2ray-configs | 307"
      - "⚡ b2n.ir/v2ray-configs | 808"
      - "⚡ b2n.ir/v2ray-configs | 268"
  - name: 手动选择
    type: select
    proxies:
      - 自动选择
      - "HK 🇭🇰 | @Raydikalx | BA65C4"
      - "SG 🇸🇬 | @Raydikalx | E246D9"
      - "🇺🇸US-198.211.4.60-0012"
      - "⚡ b2n.ir/v2ray-configs | 849"
      - "⚡ b2n.ir/v2ray-configs | 46"
      - "⚡ b2n.ir/v2ray-configs | 168"
      - "DE 🇩🇪 | @Raydikalx | 1832ED"
      - "CA 🇨🇦 | @Raydikalx | 875198"
      - "⚡ b2n.ir/v2ray-configs | 684"
      - "⚡ b2n.ir/v2ray-configs | 307"
      - "⚡ b2n.ir/v2ray-configs | 808"
      - "⚡ b2n.ir/v2ray-configs | 268"

rules:
  - MATCH,手动选择
